###

GET http://localhost:5000/post

###


GET http://localhost:3000/post?sender=eliav2

###

GET http://localhost:3000/post/62260bf39f8f7ff5c48ded71


###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message" : "this is my first message",
    "sender" : "eliav2"
}